fastlane_version "2.64.1"

default_platform :ios

platform :ios do
  before_all do
    cocoapods
  end

  desc "Run Tests"
  lane :tests do
    scan(scheme: "AssessmentApp")
  end

  desc "Push to testflight"
  lane :beta do
    match(type: "appstore",
          app_identifier: "com.pillartechnology.AssessmentApp",
          readonly: true)
    gym(scheme: "AssessmentApp",
        workspace: "AssessmentApp.xcworkspace",
        clean: true)
    pilot(username: "services@pillartechnology.com")
  end
end 
