fastlane_version "2.64.1"

default_platform :ios

platform :ios do
  before_all do
    cocoapods
  end

  desc "Run Unit Tests"
  lane :unit_tests do
    scan(scheme: "AssessmentApp")
  end

  desc "Runs UI Tests"
  lane :ui_tests do
    scan(scheme: "AssessmentAppUITests")
  end

  desc "Push to testflight"
  lane :beta do
    match(type: "appstore",
          app_identifier: "com.pillartechnology.AssessmentApp",
          readonly: true)
    gym(scheme: "AssessmentApp",
        workspace: "AssessmentApp.xcworkspace",
        clean: true)
    pilot
  end
end 
